### ISSUE TITLE
[web-animations-1] suggestion: make Animation play method more convenient (add 'time' parameter)

### ISSUE THREAD

**Issue by forceuser** [w3c/web-animations#103]
Is it possible to add "time" parameter to Animation.prototype.play(time), it will set starting point of animation and will be shorhand for setting currentTime property.
Now it takes two steps:

```
animation.play();
animation.currentTime = 1200;
```

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2051
