### ISSUE TITLE
Do we need easing and composite on PropertyIndexedKeyframe?

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#131]
As @heycam points out, you can already specify them for the whole animation on the KeyframeTimingOptions argument

**Comment by heycam** [comment]
I realise as well that while PropertyIndexedKeyframe.composite has a way to defer to the value from the KeyframeTimingOptions, there's no way to do that for PropertyIndexedKeyframe.easing.

**Comment by birtles** [comment]
The difference, however, is that when you set "easing" or "composite" on a property-indexed keyframe it should be set on each individual keyframe, not the animation. So I think we *do* need this.
