### ISSUE TITLE
PropertyIndexedKeyframes.composite should not have an optional value

### ISSUE THREAD

**Issue by heycam** [w3c/web-animations#132]
If in #131 we decide to keep PropertyIndexedKeyframes.composite, it would be more idiomatic to define it as:

```idl
  CompositeOperation composite;
```

and then to define in prose what to do when the composite dictionary member is not present.

**Comment by heycam** [comment]
This is probable the case for most or all uses of nullable types and `= null` in the spec on dictionaries and operation/constructor arguments.

**Comment by birtles** [comment]
This is fixed for composite. I'm not sure if we should do the same for offset or not.
