### ISSUE TITLE
define exactly how CSS property value taking IDL things are parsed

### ISSUE THREAD

**Issue by heycam** [w3c/web-animations#134]
We should define exactly how IDL things that take CSS property values are parsed.  For example, for easing values, the spec gives the CSS grammar to parse against, but it's not clear that we should use the CSS parser.  This would make it clear that for example `"Ease\\2d in-out"` and `"linear /**/"` would parse.  (This is the approach we're using in SVG.)

**Comment by birtles** [comment]
This should now be covered by step 7 of http://w3c.github.io/web-animations/#processing-a-frames-argument
