### ISSUE TITLE
Define how longhands and shorthands behave when specified on a keyframes object.

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#136]
Proposal: longhands override shorthands, shorthands with fewer longhand components override those with more longhand components, and for shorthands with equal numbers of longhand components, IDL name order is used.

**Comment by birtles** [comment]
If we're going to allow using 'margin-left' as a property (instead of requiring marginLeft) then we'll *also* need to specify the priority of 'margin-left' vs 'marginLeft'.

**Comment by birtles** [comment]
I discussed whether we should support <code>'margin-left'</code> or not with Shane and Tab at TPAC in October. The trouble is we have to choose one as the canonical form for the result we return from getFrames. If we return *both* from <code>getFrames()</code> then we'll have trouble because if the author updates one and then passes the result back to <code>setFrames()</code> we'll have to choose which one to listen to (and if we choose a different one to the author there will be frustration all around).

I'm pretty sure we agreed, therefore, to just support <code>marginLeft</code> as the most idiomatic form for JS.

**Comment by birtles** [comment]
Currently following up on the behavior implemented in Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1208951#c50

**Comment by shans** [comment]
The proposed resolution order SGTM
