### ISSUE TITLE
Link to processing model in Overview.src.html doesn't seem relevant

### ISSUE THREAD

**Issue by mgiuffrida** [w3c/web-animations#138]
The [definition of sampling](https://w3c.github.io/web-animations/#sampling) points to https://html.spec.whatwg.org/multipage/webappapis.html#processing-model-9 which seems to be related to network timing.

**Comment by birtles** [comment]
The link used to be right but it looks like HTML has been updated and is now doing some redirect from webappis.html to comms.html.
