### ISSUE TITLE
Update error handling for timing parameters

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#143]
As discussed with Google in February, we don't need to preserve erroneous values for timing parameters.

Meeting notes: https://docs.google.com/document/d/1lQbgJ0fZYGn1_qboj59G-MOILK33z4kmBdjgtSHF2gA/edit#heading=h.cioj28lsgoa2

**Comment by birtles** [comment]
@domenic If we are passed a negative value for duration (which we currently don't allow) should we be throwing a **RangeError** or a **TypeError**?

I notice there's [some](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27283) [advice](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27284) that suggests that all invalid arguments should be **TypeError**. Is that right?

**Comment by domenic** [comment]
`RangeError` is more JavaScriptey to be honest, but existing IDL bindings all do TypeError (e.g. `[EnsureRange] unsigned long long`), so it's kind of a tossup. If possible I'd let IDL handle this; see https://w3ctag.github.io/design-principles/#numeric-types

**Comment by birtles** [comment]
Thanks. Unfortunately duration is an unrestricted double, so `[EnforceRange]` doesn't help us here as far as I can tell. So it sounds like we should do TypeError in case WebIDL grows a way of doing `[EnforceRange]` for doubles.
