### ISSUE TITLE
[web-animations-1] Add parameter to getAnimations for getting animations in descendants too

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#146]
As discussed and minuted here: The ideas we came up with are here: https://docs.google.com/document/d/1lQbgJ0fZYGn1_qboj59G-MOILK33z4kmBdjgtSHF2gA/edit#heading=h.cioj28lsgoa2

A more concrete elaboration on that proposal is described here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1254761#c0

**Comment by birtles** [comment]
I discussed this with Antoine at one point and I think we were leaning against adding this.

**Comment by graouts** [comment]
Yes, I don't think this is warranted, JavaScript can be efficiently used to filter results of getAnimations() calls. I suggest we close this.

**Comment by birtles** [comment]
Yeah I agree about dropping the filter feature. I wonder if we might still want something along the lines of `{ subtree: true }` for getting all animations from a node and its descendants (like MutationObservers). We've actually implemented that in Firefox but only turned it on for internal users--we use it for our DevTools and for UI code.

If we do go ahead with that then we might want something more extensible than a bool (although at the same time aligning with MutationObserver is nice). I'm not sure if we'll eventually need a third value for crossing shadow DOM boundaries or if that's even possible?

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2058
