### ISSUE TITLE
Specify how unrecognized paced properties are handled

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#152]
https://w3c.github.io/web-animations/#issue-5da8463f

Suggestion: We throw if the specification doesn't match the grammar, but we fall back to distribute if the property isn't recognized (and produce a console warning). This lines up with how we generally handle properties: we assume that UAs will differ in which properties they support and so we should avoid catastrophic failure in that case (i.e. throwing an exception).

**Comment by tabatkins** [comment]
Agree - unrecognized values should be rejected and use the default value.

Tangential: You can use `<pre class=prod>` to trigger autolinking of the grammar things like `|`. You can also use `<<ident>>` directly; previously it linked to a definition in MQ, but I just updated the specs to have the definition live in V&U.

**Comment by birtles** [comment]
Thanks Tab! That's great!
