### ISSUE TITLE
TypeScript Definition

### ISSUE THREAD

**Issue by chingyawhao** [w3c/web-animations#153]
Is there support for TypeScript?
Or is there any alternative for TypeScript?

**Comment by Martin-Pitt** [comment]
@chingyawhao you could probably use the WebIDL and convert it to TypeScript definitions:
https://github.com/RicoP/idl2typings

Sources:
https://github.com/ternjs/tern/issues/419
https://github.com/Microsoft/TypeScript/issues/3027

**Comment by chingyawhao** [comment]
How do I get this WebIDL?

**Comment by birtles** [comment]
It's all here: https://w3c.github.io/web-animations/#idl-index

Note that there's some manual handling of keyframe objects that can't be expressed in WebIDL. Note sure if TypeScript can help with that.

**Comment by chingyawhao** [comment]
wew...thanks
I ll try it out
