### ISSUE TITLE
Support for custom timing functions

### ISSUE THREAD

**Issue by Ceane** [w3c/web-animations#155]
Yesterday, Webkit released support for a `spring()` timing function in Safari Tech Preview. Support for custom timing functions will empower developers to implement custom web animations with the full power of this API.

**Comment by rachelnabors** [comment]
Is there any documentation around this timing function anywhere?

**Comment by Ceane** [comment]
There's no documentation for this yet, but here is some info from [this commit](http://trac.webkit.org/changeset/201706).

**Comment by tabatkins** [comment]
Talked to @dino about it; it's just in the experimental builds, not public, and they'll be trying to spec it soon. Closing this issue for now, as it's premature; Dino can open a fresh one about spring() when they're ready.

**Comment by rachelnabors** [comment]
Fascinating, @dino. I've been trying to get the W3C into complex cubic-bezier curves for awhile now. Could use a partner.

**Comment by grorg** [comment]
Unfortunately I'm not @dino on github (or twitter, or nearly anything. I remember when dino.com was available and I thought "this web fad won't last")

Anyway, yes, it's experimental at the moment. It was necessary for some internal clients, so it won't be exposed to the Web before we have a public discussion in the FXTF.

Having said that, we've found these types of spring animations to be extremely popular with designers and it was very easy to implement. I'll write a specification proposal soon, with an example implementation in JS.

**Comment by rachelnabors** [comment]
I hear you, @grorg! I've been arguing we need a way for designers to realize their springy destiny for awhile now. They also need a format for complex timing functions, like the timing graphs from After Effects. Such a format could be the foundation for other timing functions like `spring()` in the future.

May I invite you to [participate in this conversation](https://github.com/w3c/csswg-drafts/issues/229)?
