### ISSUE TITLE
Question: how to get *all* the animations of an element

### ISSUE THREAD

**Issue by belen-albeza** [w3c/web-animations#158]
`Element.getAnimations` only returns those animations that are currently running. It would be useful to have a way to get all the animations that an element has attached, regardless of they being played or not (specially for modifying animations created with CSS).

Is there a way to achieve this and I missed it?

**Comment by birtles** [comment]
It returns animations that are currently running, those that are scheduled to run but have not yet started, and those that have finished but are filling forwards. The only animations it does not return are those that have finished and are not filling, and those that have been cancelled / never scheduled.

For script-generated animations, _not_ returning animations that have finished and are not filling is important since otherwise user-agents need to retain all animations generated forever. What's the specific effect you're trying to achieve?

**Comment by belen-albeza** [comment]
> What's the specific effect you're trying to achieve?

It's typical in CSS to define animations that are not necessarily scheduled in time, but triggered by an event (ex: a mouse over). If we could access those animations to modify their properties like we do with running animations, it would be great. A specific use case re: accessibility would be this one:

A website/app that has animations in its UI. For instance, panels sliding when appearing, avatars made bigger when mouse overs, buttons changing colors when clicked, etc. People that are sensitive to movement (motion sickness) might want to reduce the speed of the sliding panels and or the size of the avatars change, or disable the animations altogether. People who are sensitive to things flashing (like people with epilepsy) might want to disable flashing or color changing. People with visual difficulties might want to make the avatar change bigger, and the change of colors more radical.

If we could use the Web Animations API to modify the settings of these animations on demand, we could let users set their preferences regarding animations.

The alternative right now would be to _not_ define this with CSS and rely 100% in JavaScript to trigger these. But it's way overkill to do this in JavaScript, when a simple mouseover animation could (and people will make continue to do it) be defined in CSS.

**Comment by tabatkins** [comment]
> It's typical in CSS to define animations that are not necessarily scheduled in time, but triggered by an event (ex: a mouse over). If we could access those animations to modify their properties like we do with running animations, it would be great.

Those animations aren't applied to the element until the event actually occurs - they're only associated with the element in the program logic, not in any actual machine-trackable way, so there's no way an API can return them anyway.

**Comment by birtles** [comment]
Sorry for the delay (PTO). If the use case here is "I want to use CSS markup to define my animations, tweak them in JS, but trigger them in CSS" then a few things you can do are:

* Make the animation `animation-play-state: paused`, grab the animation and tweak it, then trigger with JS, eg. using `play()` which will override `animation-play-state` (doesn't quite match your use case)
* Listen for `animationstart` events and fetch the animation and tweak it then. (For CSS Transitions there's no `transitionstart` yet but it is in the draft spec for level 2. In Firefox, we have an internal "animation observer" interface that DevTools uses to detect new animations--I'm pretty sure Chrome has something similar and I suspect in the future we'll spec this as a public API.)
* Trigger a dummy CSS animation, get its timing object and list of keyframes and use that to create a new `Animation` which you control purely from JS. This will be easier once browsers implement the `KeyframeEffect` copy constructor (specced but not implemented anywhere yet). In fact, in future you should be able to do:
```js
var anim = elem.getAnimations({ animationName: 'bounce' })[0];
anim.effect = new KeyframeEffect(anim.effect); // Make mutable copy
// tweak anim.effect
// Then |anim| will still respond to changes in animation-play-state

But, one caveat, no-one ships `Element.getAnimations()` yet! That's because we need to properly spec the mapping from CSS to Web Animations and make sure we have interop there before we start to expose that. You'll notice it works in non-release channels of Firefox only (i.e. DevEdition and Nightly).
```

**Comment by belen-albeza** [comment]
Thanks @birtles for your suggestion. It seems that for that use case, the second option would be best, but since it's not implemented yet I'll stick to not having the animations in CSS but to create them in JS.

Thanks for the heads up about `Element.getAnimations`. Is there any other property/function available on Firefox Developer Edition that will _not_ be shipped in the next Firefox release?

**Comment by birtles** [comment]
Yes, lots of features in Developer Edition won't be shipped. The only features which will be shipped are listed here:

  https://groups.google.com/forum/#!topic/mozilla.dev.platform/2INRr96R3IU

Except that the `ready` attribute (promise) won't be shipped.
