### ISSUE TITLE
Processing a keyframes argument & animatable custom properties

### ISSUE THREAD

**Issue by jyc** [w3c/web-animations#163]
The CSS Houdini Properties & Values API allows authors to register custom properties that are animatable.<sup>[1]</sup> The Web Animations API allows for specifying keyframes using JS objects whose property names are animatable property names converted to IDL names:<sup>[2]</sup>

> Build up a list of animatable properties as follows:
> 1. Let animatable properties be a list of property names (including shorthand properties that have longhand sub-properties that are animatable) that can be animated by the implementation.
> 2. Convert each property name in animatable properties to the equivalent IDL attribute by applying the animation property name to IDL attribute name algorithm.

Now that custom properties can be animated to, there should be a way for authors to include custom properties in keyframes arguments as well. @birtles indicated the main issue is determining a mapping between custom property names and JS object property names.

(As an aside, CSSOM has a similar issue, e.g. Firefox and Chrome both don't support `window.body.style["--custom"]`. xidorn pointed out on Mozilla #layout this would be trickier to fix.)

@shans What are your thoughts?

[1]: https://drafts.css-houdini.org/css-properties-values-api/#animation-behavior-of-custom-properties
[2]: https://w3c.github.io/web-animations/#processing-a-keyframes-argument

**Comment by shans** [comment]
I think we can pretty trivially detect custom property names by the double-dash at the beginning. So a keyframe can just contain custom property declarations and this will map naturally?

**Comment by shans** [comment]
(btw the [] accessor on Element.style isn't specced to allow access to custom properties and may never be.)

**Comment by birtles** [comment]
Thanks @shans. I was wondering if we need to map '--custom' to something more JS-like, but I think I agree we can just leave it as-is.

**Comment by birtles** [comment]
I'm trying to spec this but I can't work out from the Properties & Values spec what the scope is of custom properties. @jyc? @shans?
Basically I need to add a step like, "Add to _animatable properties_ the _name_ of any custom properties registered against the active document of the current realm" or something.

**Comment by jyc** [comment]
I think they are scoped to the window (buried in an issue: https://github.com/w3c/css-houdini-drafts/issues/216#issuecomment-224972952 ).

**Comment by shans** [comment]
That issue is talking about the scope of property registration, which I don't think is what you want.

Notionally, *every* custom property exists with a default invalid value. Hence, if a custom property is defined in a set of keyframes, then it should animate (as a 50% flip by default) and be observable on the animated element.

This is what happens already with CSS animations - something like

```
.bar { animation: foo 1s; }

@keyframes {
  0% { --far: zero; }
  100% { --far: one; }
}
```

will induce a custom property --far on any element of class 'bar', for the duration of the animation, independent of any custom property registration.

**Comment by birtles** [comment]
Ok, I think our main requirement with having an open-ended set is simply reading the properties in a consistent order in case getters have side effects. But perhaps we can use [EnumerableOwnNames](http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames) (which I don't *think* has side effects), and simply keep any properties that begin with '--', then sort them before reading them.
