### ISSUE TITLE
Reversing an animation with a negative delay means it never finishes

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#166]
Test case: https://jsfiddle.net/g7ubn9te/

From my monologue on [#webanimations](ircs://irc.w3.org:6667/%23webanimations):
> 15:33 &lt;birtles&gt; oh, I think I found a fairly decent bug in the spec
> 15:33 &lt;birtles&gt; basically, this test case: https://jsfiddle.net/g7ubn9te/
> 15:33 &lt;birtles&gt; in Firefox it fills
> 15:34 &lt;birtles&gt; (regardless of the fill mode)
> 15:34 &lt;birtles&gt; in Chrome it doesn't
> 15:34 &lt;birtles&gt; (regardless of the fill mode)
> 15:34 &lt;birtles&gt; Firefox is doing the correct thing by the spec but it's not particularly intuitive
> 15:34 &lt;birtles&gt; basically finishing behavior and phases don't line up
> 15:35 &lt;birtles&gt; Finishing behavior: once you get to zero stop
> 15:35 &lt;birtles&gt; Phases (on which fill modes are based): the boundary between the before phase and active phase can be negative
> 15:36 &lt;birtles&gt; so basically, the spec says that when you play backwards keeping going until you get to zero and then stop, even if that means you remain forever stuck in the active phase
> 15:51 &lt;birtles&gt; I'm actually not sure what the preferred result is
> 15:51 &lt;birtles&gt; on the one hand I'm tempted to say we should play backwards to the beginning of the delay, even if that time happens to be sub-zero
> 15:51 &lt;birtles&gt; but I think we deliberately wanted the negative delay to give you that kind of clipping effect
> 15:52 &lt;birtles&gt; if that's the case then we probably should still not fill indefinitely
> 15:54 &lt;birtles&gt; but achieving that would probably mean you could never seek into the negative range, i.e. it's completely clipped, not just shifted on the timeline
> 15:56 &lt;birtles&gt; so I think we want to play backwards to the beginning of the delay, even if that happens to be sub-zero

**Comment by birtles** [comment]
Ok, I've been thinking about this all night and here's what I've thought so far.

## What is delay for anyway?

Start delay does at least two very useful things:

* It controls the initial play head position (e.g. lets you have a delayed reaction for an animation triggered off an event, or even start part-way through the animation using a negative value&mdash;particularly common for manually seeking a CSS animation)
* In the context of groups, and particularly sequence groups, lets you tweak the relative timing of children. (e.g. in a sequence A, B, C, lets you shift B, so that there's a bit of a gap between the end of A and the start of B; or, using a negative delay, lets you overlap the end of A with the start of B)

As for end delay, it was originally added to support SVG's `min` attribute, i.e. make an animation effectively take longer for the purposes of sequencing. That's all it *has* to do, but in the context of sequence groups, it's conceivable that a negative value might be useful to say, "look, the last 3s of this animation is really long and unimportant so you shouldn't wait for it to finish before running the next thing in this sequence". In that sense, both start and end delay behave like the temporal equivalent of `margin`, adding or removing space between siblings.

## Clipping vs shifting

Once we introduce animation finishing behavior (that is, where we define a natural end where an animation's current time stops increasing), however, we suddenly face the issue of whether delays effectively clip the effect or simply influence the playback position.

I think there are at least three models here:

1. Delay never clips, only influences _initial_ playback position
2. Delay always clips, content outside the delay range is inaccessible
3. Delay doesn't clip, but confines range of playback

The complication comes from having two different kinds of boundaries. Phase boundaries determine when, in the absence of a fill mode, the animation switches from producing an effect, to having no effect. Or, another way of phrasing it, is that the phase boundaries determine when the fill mode is applied. Finishing boundaries determine where the playhead stops in the current direction.

We'll look at each model in turn, but first let's start with what we currently do.

### 0. What we currently do

Currently, we don't do any of the above. In the forwards direction the finishing boundary is always &ge; the phase boundary. That means that a negative end delay clips, i.e. you cannot play the range clipped by the negative end delay. Even if you seek into that range and have a forwards fill, you'll just get the value corresponding to where the negative end delay clipped back to. Furthermore, if you seek past the negative end delay and play in reverse, you'll see nothing until you get to the end delay point. It is completely clipped, gone, extinct. That's just odd.

So far, this is (2) from above, but in the negative direction, it's different. In the negative direction the finishing boundary is always zero. _However_, the phase boundary (for the end of the animation), can be negative. This is the issue in this bug. You can have a situation where you reach the finishing boundary but have not reached the phase boundary so the fill mode fails to apply.

Diagrammatically, it looks like this:

![Model 0, how delays currently work](https://cloud.githubusercontent.com/assets/1232595/17796584/7df9ee04-65fc-11e6-810c-552b8cc4bd31.png)

**Key:**
Blue = start delay
Green = end delay
Down arrow = where `play()` starts from
Sideways arrow = the finishing boundary
Yellow shade = phase boundary where the fill:forwards/backwards takes effect for the current direction

### 1. Delay never clips, only influences _initial_ playback position

Keeping with the margin analogy, we'd like to say that delay never clips, only positions things. There are a few problems however:

* People appear to want to use a negative end delay to limit the playback range (see issue #154)
* If we limit the playback range based on negative delays, we also need to adjust the phase limits so we don't end up with the problem that triggered this issue (i.e. finishing boundary occurs before phase boundary meaning fill mode doesn't work)
* If we limit the phase boundary we basically end up with (2), i.e. clipping
* If we _don't_ limit the playback range based on negative delays we have a slightly odd situation where, for example, in the reverse direction we keep playing until the end of the active interval (some negative value), then when we call `reverse()` we'll jump to current time = 0. Also, we'd fail to address the use case in issue #154.

### 2. Delay always clips, content outside the delay range is inaccessible

This completely breaks the margin analogy. I think it also breaks using negative delays in sequence groups since any negative time will just be converted to zero when we calculate the active time. I also think that it overlaps quite heavily with using `iterations` / `iterationStart` and people can probably use those to get the same kind of effects when needed.

### 3. Delay doesn't clip, but confines range of playback

In this approach we make two changes to the current setup:

1. We change the calculation of active time so that even if we're in the before/after phase, if we are filling and if the local time is within the active duration, we still calculate the active time in the same way as we do in the active phase.
2. We fix the calculation of the before-active phase boundary to be something like `max(start delay, 0)`.

That would mean that the end delay continues to confine the playback range, but you could seek to outside that range, and, provided you have the right fill mode, still see the remainder of the content. Incidentally, I think that might also fix what sequence groups do.

Diagrammatically, it looks like this:

![Model 3, proposed changes](https://cloud.githubusercontent.com/assets/1232595/17796955/9f5f15c6-65ff-11e6-9550-44ba0b0588d6.png)

The one disadvantage I see of doing this is that, say, for example, you have an animation with a start delay of -2s. What this approach does is define the before-active phase boundary as zero. That's so that when you play in reverse and hit zero, you apply the fill mode at that point. If, however, you wanted to seek to -2s and play the animation from its actual start, well, you could only do that if you have a backwards fill mode. If you had a fill mode of 'none', you'd just see nothing until you hit zero.

I think this model 3 is probably the most reasonable so I might try implementing it in Firefox and see what breaks as a result. @shans @dstockwell @suzyh @alancutter @danwilson @tabatkins @hiikezoe &mdash; any comments? It's a change to shipping behavior but Firefox and Chrome already don't agree so something has to change (I'm suggesting both).

**Comment by shans** [comment]
I think I understand this, and I think your suggestion is the most reasonable approach. It's .. complicated .. though so I want to talk it through with Doug as well to make sure.

Fortunately, the very complication and edge-case-iness of this means that changes shouldn't have much impact on existing users, so it should be easy to modify what we do.

**Comment by shans** [comment]
A consequence of your preferred option is that a negative start delay forces what looks like a backwards fill, and a negative end delay forces what looks like a forwards fill (unless you start to put things in groups, etc.). Obviously you can seek outside of the play range and see the real fill but this isn't going to magically happen for you.

I'm OK with this, I think, because as you point out you can get the proper fill behavior by using iterationStart and iterations instead.

**Comment by birtles** [comment]
> A consequence of your preferred option is that a negative start delay forces what looks like a backwards fill, and a negative end delay forces what looks like a forwards fill (unless you start to put things in groups, etc.). Obviously you can seek outside of the play range and see the real fill but this isn't going to magically happen for you.

Oh, that's not the intention or what I expect. It should be almost the opposite. i.e. fill modes are now respected and if you seek into the negative delay area it is _not_ fixed to the value that coincides with where the delay finishes. I've just tried implementing it in Firefox and it seems to work so far.

**Comment by birtles** [comment]
With this change, the [original test fiddle](https://jsfiddle.net/g7ubn9te/) now reflects the fill mode as expected.

Furthermore, for the following test:
```js
var anim = div.animate({ transform: [ 'translate(0px)', 'translate(300px)'] },
                       { duration: 2000, endDelay: -500, fill: 'forwards' });
anim.play();
anim.onfinish = () => {
  setTimeout(() => { anim.currentTime += 250; }, 500);
  setTimeout(() => { anim.currentTime += 250; }, 1000);
  setTimeout(() => { anim.currentTime += 250; }, 1500);
};
```

you can seek into the negative delay region and the animation updates but not beyond the end of the active duration.

(For my own reference, if I add some reverse like below I do see a little flicker at the end of the reverse but that appears to be a bug related to synchronization with the compositor&mdash;if I use `marginLeft` instead there's no flicker.)

```js
var anim = div.animate({ transform: [ 'translate(0px)', 'translate(300px)'] },
                       { duration: 2000, endDelay: -500, fill: 'forwards' });
anim.play();
anim.onfinish = () => {
  setTimeout(() => { anim.currentTime += 250; }, 500);
  setTimeout(() => { anim.currentTime += 250; }, 1000);
  setTimeout(() => { anim.currentTime += 250; }, 1500);
  setTimeout(() => { anim.reverse() }, 2000);
  anim.onfinish = null;
};
```

Running web-platform-tests with this change I get six failures and they seem to be tests specifically testing these corner cases so I'm optimistic this is not going to affect existing content significantly:
```log
Unexpected Results
==================

/web-animations/interfaces/AnimationEffectTiming/getComputedStyle.html
----------------------------------------------------------------------
FAIL change currentTime when fill forwards and endDelay is negative
/web-animations/timing-model/animation-effects/active-time.html
---------------------------------------------------------------
FAIL Active time in after phase with forwards fill and negative end delay greater in magnitude than the active duration is zero
FAIL Active time in after phase with forwards fill and negative end delay greater in magnitude than the sum of the active duration and start delay is zero
/web-animations/timing-model/animation-effects/current-iteration.html
---------------------------------------------------------------------
FAIL Test end delay: duration:100 delay:1 fill:both endDelay:-200
/web-animations/timing-model/animation-effects/phases-and-states.html
---------------------------------------------------------------------
FAIL Phase calculation for an animation effect with a negative start delay
/web-animations/timing-model/animation-effects/simple-iteration-progress.html
-----------------------------------------------------------------------------
FAIL Test end delay: duration:100 delay:1 fill:both endDelay:-200
```

**Comment by birtles** [comment]
So I think the specific changes to the spec would be:

In [animation effect phases and states](https://w3c.github.io/web-animations/#animation-effect-phases-and-states):
```diff
- before active boundary: min(start delay, end time)
+ before active boundary: max(start delay, 0)
```

In [calculating the active time](https://w3c.github.io/web-animations/#calculating-the-active-time):
```diff
 If the animation effect is in the before phase,
     The result depends on the first matching condition from the following,
 
       If the fill mode is backwards or both,
-          Return zero.
+          Return max(local time - start delay, 0).
 
       Otherwise,
           Return an unresolved time value.
 
 If the animation effect is in the active phase,
     Return local time - start delay.
 
 If the animation effect is in the after phase,
     The result depends on the first matching condition from the following,
       If the fill mode is forwards or both,
-          Return the result of evaluating max(min(active duration, active duration + end delay), 0).
+          Return the result of evaluating min(local time - start delay, active duration).
 
       Otherwise,
           Return an unresolved time value.
 
 Otherwise (the local time is unresolved),
     Return an unresolved time value.
```

**Comment by birtles** [comment]
Had a very helpful chat with @shans who points out that this doesn't work well with groups. Particularly if you have the following arrangement:

```
sequence([Animation(foo, bar, {endDelay: -500, duration: 2000}),
          Animation(far, bar2, {duration: 2000})])
```

Then you'd expect to have a group that runs for 3500ms with 500ms overlap in the middle&mdash;but you won't because the first animation will have a fill mode of `auto` &rarr; `none`. Since the active time past the active-after boundary is controlled by the fill mode, the first animation will stop having an effect at 1500ms.

We went over a couple of options:

1. Take the current behavior in the spec that applies to negative start delays and apply it to negative end delays too. That is, if you use a negative end delay, then when you reach the end you'll be stuck in the active phase&mdash;the fill mode will be ignored.
2. Rework fill modes for group children. No concrete proposal here but we already default to an `auto` fill mode so we have some room to interpret what that means for group children once we introduce groups. In the past we have discussed other situations where fill modes beyond the current set would be useful so perhaps adding other fill modes is worth considering.

(One point to bear in mind regarding (2), is that simply saying, "for group children 'fill: auto' means 'fill: both'" probably doesn't cut it. The reason is that if you do that, then not only do you allow the animation to run during any negative delay interval, but you also force it to fill to the start/end of its group and for many cases that's probably not what you want.)

So, this is going to take some more thought.

**Comment by birtles** [comment]
So I went to make this change in the spec and Firefox and discovered that the initial formulation above doesn't really work because in some cases the before phase and after phase overlap.

Given the following conditions:

* The finish time in a given direction is never "before" the corresponding phase boundary (the original cause for this bug)
* Before phase and after phase never overlap (I think this requirement is self-evident, otherwise we'd have to define what happens, for example, what the behavior is when they overlap and the fill mode is 'backwards' or 'forwards', not 'both' or 'none')
* The start time in the forwards direction is always zero (needed in order for a negative start delay to have the desired effect of starting mid-way)

There are still a number of possible solutions. If we add the further condition:

* The finish time in a given direction equals the start time in the opposite direction
(This will also imply that the finish time for a given direction is "after" its start time or cotemporal with it)

then I think we narrow it down to the following arrangement.

![proposal-a](https://cloud.githubusercontent.com/assets/1232595/17876454/34c89372-6915-11e6-8585-41d8246e26ab.png)

From a spec point of view this is basically:

In [animation effect phases and states](https://w3c.github.io/web-animations/#animation-effect-phases-and-states):
```diff
- before-active boundary: min(start delay, end time)
+ before-active boundary: max(min(start delay, end time), 0)

- after-active boundary: min(start delay + active duration, end time)
+ after-active boundary: max(min(start delay + active duration, end time), before-active boundary)
```

In [calculating the active time](https://w3c.github.io/web-animations/#calculating-the-active-time):
```diff
 If the animation effect is in the before phase,
     The result depends on the first matching condition from the following,
 
       If the fill mode is backwards or both,
-          Return zero.
+          Return max(local time - start delay, 0).
 
       Otherwise,
           Return an unresolved time value.
 
 If the animation effect is in the active phase,
     Return local time - start delay.
 
 If the animation effect is in the after phase,
     The result depends on the first matching condition from the following,
 
       If the fill mode is forwards or both,
-          Return the result of evaluating max(min(active duration, active duration + end delay), 0).
+          Return the result of evaluating max(local time - start delay, 0).
 
       Otherwise,
           Return an unresolved time value.
 
 Otherwise (the local time is unresolved),
     Return an unresolved time value.
```

In calculating the [end time](https://w3c.github.io/web-animations/#end-time):

```diff
+ The end time of an animation effect is simply the sum of its start delay, active duration, and end delay.
- The end time of an animation effect is max(start delay + active duration + end delay, 0).
```

This works pretty well. Only two tests fail (`phases-and-states.html` which is testing exactly this, and another computed timing one) so I'm fairly confident this isn't a significant change that will break anything.

The phases when you have a large negative delay, however, seem a little surprising in that they don't bear much correspondence to the active interval at all.

If we're prepared to relax that requirement (and also allow for the finish time to occur "before" the start time) then we could possibly also have the following arrangement.

![proposal-b](https://cloud.githubusercontent.com/assets/1232595/17876545/15ba4dee-6916-11e6-86db-dd42f5f82a98.png)

This is a more involved change, that involves defining an 'effect start' concept (something like `min(start delay, 0, end time)`) and using that in a bunch of places. However, in my testing so far, even fewer tests fail with this (the computed timing one from above).

Comparing this to the existing spec:

![current-spec](https://cloud.githubusercontent.com/assets/1232595/17876572/735f4404-6916-11e6-99ad-dc509d4ed37a.png)

And, for reference, this is what I currently see in Chrome Canary:

![current-chrome](https://cloud.githubusercontent.com/assets/1232595/17876583/82ecaa2e-6916-11e6-832d-2f82c5963d67.png)

For reference, this is the fiddle I'm using to generate the diagrams: https://jsfiddle.net/jsj25wnc/5/

**Comment by birtles** [comment]
I'm still unsure which way is the best way to fix this. I'm leaning towards the second approach from the above comment, i.e. add the "effect start time" concept. This is the more risky change since it affects a few things like where `finish()` jumps to when running in reverse with a negative start delay.

As an example, consider:
```js
var anim = elem.animate(..., { duration: 2000, delay: -500 });
anim.playbackRate = -1;
anim.play();
```

Currently this will cause the animation to jump to active time 2s and play through to active time 0.5s. With the suggested change, however it will cause the animation to play from active time 0.5s to 0s. That's because we no longer treat _local time_ 0s as the 'finish' time when running in reverse so when we get the call to `play()` we don't invoke the auto-rewind behavior.

However, I still lean towards this since I think it makes the behavior of `fill: forwards` / `fill: backwards` much more logical.

The argument for the other approach, however, is that just as a negative end delay limits your playback range going forwards, a negative start delay should limit your playback range going backwards. So there is a symmetry there, even if the before/after phases don't appear to be particularly symmetrical.

I could go either way, I think. @shans? @dstockwell? Thoughts?

**Comment by birtles** [comment]
Having discussed this with @shans, I'm going to go ahead and apply the first approach from above.
