### ISSUE TITLE
Explicitly define what should happen when AnimationEffectTimingProperties.iterationStart is greater than iterations

### ISSUE THREAD

**Issue by a2sheppy** [w3c/web-animations#170]
While the spec describes (at https://w3c.github.io/web-animations/#iteration-start, https://w3c.github.io/web-animations/#dom-animationeffecttiming-iterationstart, and https://w3c.github.io/web-animations/#dom-animationeffecttimingreadonly-iterationstart) what should happen if the value of `iterationStart` is set to less than 0, it fails to describe what should happen if it's greater than the value of `iterations`.

What should an implementation do if the starting iteration is larger than the total number of iterations? I would assume this would either cause the animation to simply not play or throw a `TypeError` just like specifying a negative value does, but since the spec doesn't say, this leaves things open to confusion and implementation incompatibilities.

(For my own reference later, with apologies, this impacts MDN documentation for this property, located at https://developer.mozilla.org/en-US/docs/Web/API/AnimationEffectTimingProperties/iterationStart)

**Comment by birtles** [comment]
`iterations` is added to `iterationStart` (see [calculating the overall progress](https://w3c.github.io/web-animations/#calculating-the-overall-progress)) so it's quite ok for `iterationStart` to be larger than `iterations`.

e.g. if you have `iterationStart` of 5 and `iterations` of 3, the animation will still play 3 times but it will have a `currentIteration` beginning at 5 (which really only makes a difference when you have an `iterationComposite` mode of "accumulate").

**Comment by birtles** [comment]
Closing this now since I haven't heard any response to suggest the spec needs to change.

**Comment by a2sheppy** [comment]
Yeah, I see that... except that it isn't really natural to think of it being okay for the current iteration number to be larger than the total number of iterations; it there are supposed to be 3 iterations and you tell it to start on the 5th iteration, that doesn't make sense. It's a request to exceed the maximum that was previously set, or seems to be.

It's like telling someone to think of San Francisco as the starting point, Boston as the ending point, then putting them on a boat in the middle of the Atlantic and asking them to walk 5 miles to the east

**Comment by birtles** [comment]
`iterations` doesn't define your end point, just how many times you iterate. `iterationStart` defines where you start. It's like telling someone to walk 3 blocks and putting them 5 blocks away to begin with.

Being able to specify `iterationStart` > `iterations` is useful when you have an `iterationComposite` mode of 'accumulate' since the absolute value of `currentIteration` is significant. Furthermore, being able to specify `iterationStart` = 0.5 and `iterations` = 0.5 lets you play the second half of the animation in a duration-independent manner.
