### ISSUE TITLE
Provide method to stop or pause animation for users affected by animation

### ISSUE THREAD

**Issue by nattarnoff** [w3c/web-animations#176]
Animation is a key component to the internet. Building better, more performant animation tools is key, however there is a significant number of users that are affected by animation and can become physically ill. This varies by user from minor annoyance to severe vertigo, nausea, and migraines. Providing users with control similar to MacOS and iOS reduce motion can help mitigate this. 

In the CSSWG-Drafts and WCAG 2.1 repos issues have already been filed and discussed to provide [media queries in CSS](https://github.com/w3c/csswg-drafts/issues/442) and [testing guidelines in WCAG](https://github.com/w3c/wcag21/issues/18) so that animation can be accessible. The WAAPI needs some tools as well to allow pausing of JS based animations by the user. 

Ideally including a setting in the browser that the user can use inform the site to reduce or turn off animation, yet keep the site readable and usable, would be ideal.

**Comment by cookiecrook** [comment]
This should already be possible with the diff in [CSS #586](https://github.com/w3c/csswg-drafts/issues/442) 

```js
if (window.matchMedia('(prefers-reduced-motion)').matches) {
    /* reduce animation */
}
```

**Comment by nattarnoff** [comment]
The PE advocate in me (and vestibular disorder) wonders if there is a better way to word this.

The idea of animation being the default and we, as authors, need to purposely put in code to **not** animate for those users who might be susceptible has show in the past to be ignored or logged as a future enhancement like other accessibility issues and never achieved. Making accessibility the default and adding motion seems the more prudent thing.

Until the browser provides a setting, we are left with two options:

1) The author including accessibility in their build
2) The user capitalizing on a reduce motion custom style sheet.
 
In scenario 2, if the best practice code is that animation is off and **if** the `prefers-reduced-motion` setting is not true, then animate. This allows a user to override an animated website with a custom style sheet that sets reduced motion.

**Comment by cookiecrook** [comment]
The specific media feature name is being debated on the other threads. Current consolation proposal (as of an hour ago) is  the slightly more verbose:

```js
window.matchMedia('(motion-preference: reduce)').matches
```

Please comment on the CSSWG threads. I think this issue can be closed due to the general availability of `window.matchMedia`
