### ISSUE TITLE
Replacement of Penner Easings?

### ISSUE THREAD

**Issue by sdras** [w3c/web-animations#178]
I think cubic-beziers are a little limited, the two control points don't really give us room for more beautiful and advanced effects. I know it's a big ask, but are there any considerations for moving away from Penner easings and into something that's more physics-based or even just slightly more advanced out of the box simulations of different types of easing?

Thanks in advance for your time in the matter.

**Comment by rachelnabors** [comment]
Quite a bit of discussion on this front. I am gunning for a custom timing function spec that could drive other timing functions, a syntax you could export from After Effects, say: https://github.com/w3c/csswg-drafts/issues/229

A... timing function API...

**Comment by birtles** [comment]
Yes, I'll split off that spec in the next few weeks.

**Comment by sdras** [comment]
most excellent. thank you both!

**Comment by birtles** [comment]
I've split off the separate CSS timing function spec so I'm closing this for now. Please file any enhancement requests over at the csswg-drafts repo with title beginning "[css-timing-2] ...".
