### ISSUE TITLE
Stop storing invalid keyframe values

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#181]
Currently the spec requires we store invalid keyframe values (see [note at end of 'Calculating computed keyframes'](https://w3c.github.io/web-animations/#calculating-computed-keyframes)). This is simply so that paced timing produces the same result even for an implementation that does not support a particular value.

Now that we are going to drop paced timing (#180) I don't see any need for keeping invalid values. I'm not completely sure we really needed to do this anyway and it has always felt quite awkward preserving these values (we _don't_ preserve values for properties that the UA can't animate but we _do_ preserve values for properties it can animate but are invalid--that seems a bit odd). It seems more useful to the author to be able to detect a UA's support for certain properties by looking at the result of `getKeyframes()` so I propose we should *not* store invalid property values.

@suzyh @alancutter @ericwilligers @shans @dstockwell sound OK?

**Comment by alancutter** [comment]
Sounds good to me, that will match the behaviour of mutable CSSStyleDeclarations.
For the record Chrome doesn't store the original strings internally anyway.
