### ISSUE TITLE
DocumentTimeline constructor is probably a security hole

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-animations#183]
https://w3c.github.io/web-animations/#dom-documenttimeline-documenttimeline says:

> Creates a new DocumentTimeline object associated with the active document of the current browsing context.

but the active document of any browsing context need not be same-origin with the code calling the constructor, nor same origin-domain, or same anything, really.

I really doubt any browsers implementing this API do anything remotely involving getting the active document of any browsing context here.  I know for a fact Firefox does not.  It uses the document of the "current global", as defined at <https://html.spec.whatwg.org/multipage/webappapis.html#current-global-object>, which is guaranteed to be a Window in this case.

**Comment by bzbarsky** [comment]
Oh, and I should note that it's not even clear what "current browsing context" means.  But fixing this to not use "active document" will likely make that problem go away too.

**Comment by birtles** [comment]
Oops, I actually meant to push 6d2ddc934d1f931b28eca70355ac34caac3e0239 to a branch and get @bzbarsky to review. Hopefully it is ok.

**Comment by birtles** [comment]
Great, thanks Boris!
