### ISSUE TITLE
[web-animations-2] AnimationWorklet integration - using GroupEffect and allowing control of localTime

### ISSUE THREAD

**Issue by majido** [w3c/web-animations#191]
Background
----------
During last houdini F2F meeting it was decided that we should attempt to make animation worklet
API fit better within web animation model.

One of the key features of worklet animations is that they can have multiple effects which are
driven by the `animate` function in worklet scope. Our initial plan was to make a new Animation base
class that does not assume "a single effect" (see below for a initial API sketch). Since then I
realized that web animations level 2 spec has a `GroupEffect` construct which I believe worklet
animations can use to the same effect.

``` webidl
interface AnimationBase :  EventTarget{...};

interface Animation :  AnimationBase {
  attribute AnimationEffectReadOnly? effect;
  attribute AnimationTimeline? timeline;
};

interface WorkletAnimation : AnimationBase {
  attribute AnimationEffectReadOnly? effects;
  attribute array<AnimationTimeline> timelines;
}
```

Using GroupEffect with WorkletAnimations
----------------------------------------
The idea is to pass in a GroupEffect to WorkletAnimations for usecases that require controlling
multiple effects. However, In `WorkletAnimation` we want to provide a more flexible API where the
animation script has the option to set the local time for each individual child effects.

Here is a hypothetical API that can enable this:

```js
// In Document scope
animationWorklet.addModule('my-custom-animator.js').then( _ => {
  const workletAnim = new WorkletAnimation(
    'my-custom-animation',
    new WorkletGroupEffect([new KeyframeEffect(), new KeyframeEffect()]),
    document.timeline);
});
```

```js
// In Animation Worklet scope
registerAnimator('my-custom-animation', class {
  animate(timelines, groupEffect) {
    const time = timelines[0].currentTime;
    // Drive the output by setting group effect's children local times.
    groupEffect.children[0].localTime = time;
    groupEffect.children[1].localTime = time * 3.14;
  }
});

```

The current GroupEffect design only allows for two different scheduling models (i.e.,
parallel, sequence). These models govern how the group effect local time is translated to its
children effects local times by controlling the child effect start time. In parallel mode children
start times are the same as parent, and in sequence mode children start times form a sequence.

Setting local time directly on child effects does not fit in either of these models. One way to
think about it is that this model allows arbitrary per-child start time. Below is a set of proposed
changes to GroupEffect that allow this.

Proposal
--------
Keep GroupEffect as is but introduce a new subclass WorkletGroupEffect (or CustomGroupEffect).
Unlike normal group effects where parent time dictates the child time the above will allow its 
children local time to be mutated individually as well.

```webidl
partial interface AnimationEffectReadOnly {
    // Intended for use inside Animation Worklet scope to drive the effect.
    [Exposed=AnimationWorklet]
    attribute localTime;
};


interface WorkletGroupEffectReadOnly :  GroupEffectReadOnly {}

interface WorkletGroupEffect :  WorkletGroupEffectReadOnly {}
WorkletGroupEffect implements AnimationEffectMutable;
WorkletGroupEffect implements GroupEffectMutable;
```

Setting localTime property on an effect to value t does the following:

- If the animation effect does not have a parent group, then set the effect local time to t.
- If the animation effect has a parent group
    * If the parent group is a WorkletGroupEffect, then
        set the effect local time to t, and the effect start time to (parent's transformed time - t).
    * Otherwise throw an exception indicating that the child effect time can only be controlled by
      its parent group.

Notes
-------
 - Initially we don't want to expose WorkletGroupEffect directly, rather only allow it to be created
   if a sequence of effects are passed into WorkletAnimation.
 - Clone() method on WorkletGroupEffect needs to not only close timing and children but also the
   start time values.
 - Not clear to me what should happen if a child local time is set but its parent local time is
   still unresolved.

**Comment by alancutter** [comment]
@birtles Is Web Animations level 2 hosted online somewhere like http://w3c.github.io/web-animations/?

**Comment by birtles** [comment]
@alancutter Yes, https://w3c.github.io/web-animations/level-2/

**Comment by alancutter** [comment]
Perhaps making the relationship between a group animation effect and its children less constrained would be worth the flexibily it leaves for group animation effects in future. Let group animation effects specify how their duration and their children's local time are calculated and make the current level 2 specification specific to `{Group,Sequence}Effects`.

**Comment by birtles** [comment]
I don't understand what you're suggesting. It sounds like you're describing the current state of affairs.

**Comment by alancutter** [comment]
I'm suggesting to make an animation effect's local time determined by the parent group directly instead of having their start time determined by the parent group. This leaves the concept of a child animation effect's start time and inherited time as an implementation detail of `{Sequence,Effect}Group`s instead of something universal to all animation effects.

**Comment by majido** [comment]
> Firstly I don't think we want to directly set the effect's local time, per se. The above proposal has the step, "set the effect local time to t, and the effect start time to (parent's transformed time - t)", however, in level 2 of the spec, the definition of the local time is, "local time of an animation effect is the animation effect’s inherited time minus its start time". That is, the local time is calculated from the start time so we can't set both without changing the model (i.e. setting the start time should be sufficient).

Makes sense. I think the expose API to Javascript should to be in terms of "local time" but in spec we will just modify the start time so that the desired local time is achieved.

> However, one awkward result of setting the start time is that there's a dependency chain between the timing calculations that goes:
> child effect start time → child effect end time → group effect intrinsic iteration duration → group effect transformed time → child effect local time
> That is, if you're in the second iteration of a WorkletGroupEffect and you set the local time of one of its children by adjusting its start time, it's local time could then jump to a different time than you set.

Very interesting, I missed this dependency! One way around this is to define the intrinsic
iteration duration for a WorkletGroupEffect in such a way to break the dependency. For example if
the worklet group effect intrinsic duration was 0 then it will not be affected by its children.

I don't think this is a problem given that WorkletGroupEffect is really meant to be used with 
in AnimationWorklet where it is expected that one directly sets its children localTime.

> Basically, seeking arbitrary nodes in the graph is hard. Seeking the children of the root-level group is probably doable provided the group doesn't repeat, or have timing functions applied etc.

The proposal only allows seeking in immediate children of  `WorkletGroupEffect`. Also If we make
it so that the seek has no visible effect to the group's ancestors then I don't believe we need to 
limit it to the root-level.  

In particular if we break the intrinsic iteration duration dependency you mentioned above, I don't 
think ancestors see any other side effect given that we don't change the localTime of the
group.

I am not sure if I fully understand why we need to prevent repeat or application of timing functions.

> I'm suggesting to make an animation effect's local time determined by the parent group directly instead of having their start time determined by the parent group. This leaves the concept of a child animation effect's start time and inherited time as an implementation detail of {Sequence,Effect}Groups instead of something universal to all animation effects.

Interesting idea. In particular if you do that then group effects are no longer limited to only
changing the children start offset. For example, you can have a group effect that plays two effects
alternatively depending on playback direction. Combined alternative playback rate this can lead
to interesting usecases. 

Also as far as I understand it, a group scheduling have ramifications in both direction:
 1) parent   -> children:  transformed time        -> local time
 2) children -> parent  :  active duration & delay -> intrinsic iteration duration

A particular group schedule strategy (e.g., parallel or sequence) determines both above 
transformation.

**Comment by birtles** [comment]
> Very interesting, I missed this dependency! One way around this is to define the intrinsic
iteration duration for a WorkletGroupEffect in such a way to break the dependency. For example if
the worklet group effect intrinsic duration was 0 then it will not be affected by its children.

I think the difficulty with making the intrinsic duration 0 is that authors will be required to manually set it. `Animation`s use the duration of their children to perform reversing, finishing etc. Furthermore, groups use their own duration to perform repeating etc. Unless authors set the duration of these `WorkletGroupEffect`s, a lot of stuff will break. But at the same time, I wonder how realistic it is to set an accurate duration manually for some of these use cases.

Groups as currently envisaged are primarily a timing construct and it feels a little bit like we're trying to retrofit them to be largely just an object container. I wonder if [SMIL's `<excl>` containers](https://www.w3.org/TR/SMIL3/smil-timing.html#Timing-ExclSyntax) might be a source of ideas here.

I agree Alan's proposal makes sense, but I think there are still a few unresolved issues (particularly what we do with regards to the group's duration).

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2071
