### ISSUE TITLE
Drop the 'pending' state and add a separate `isPending` flag?

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#196]
It seems to me that it's often useful to be able to distinguish between "play pending" and "pause pending" (and in future "playback rate change pending").

Consider a use case I came across yesterday. In Firefox we want to [synchronize the throbber animations in tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1394985). We can easily do that with `getAnimations()`:

```js
const animations =
  tabs.getAnimations({ subtree: true })
  .filter(anim =>
    anim instanceof CSSAnimation &&
    anim.animationName === "tab-throbber-animation"
    (anim.playState === "running" || anim.playState === "pending"));

const firstStartTime = Math.min(
  ...animations.map(anim => anim.startTime === null ? Infinity : anim.startTime)
);

if (firstStartTime !== Infinity) {
  for (let animation of animations) {
    animation.startTime = firstStartTime;
  }
}
```

This works fine. The trouble, however, is that in future if we start to pause some of these animations (perhaps to indicate a stalled/crashed tab?) then that check for `"pending"` will match on a pause-pending animation. Furthermore, setting the `startTime` of a pause-pending animation will cancel the pause and make it play again which is definitely not what you want in this case.

In this case, we really only want to match playing and play-pending animations but the API doesn't let you do that. You can sometimes deduce what kind of `"pending"` it is but it's tricky, error-prone, and likely to become more difficult as we make other operations like playback rate changes async (e.g. if the `startTime` is non-`null` then it's either pause-pending or playback-rate change pending, unless, of course, it's an aborted async pause).

On the other hand, adding play states like `"play-pending"`, `"pause-pending"`, and `"playbackrate-change-pending"` to `playState` will make for very clumsy code in other cases (e.g. to detect if we're pending and hence if we need to wait on `ready`).

It seems to me that we really should have a separate `playState` member and `isPending` member. Then you can detect "playing or play-pending" by simply checking `playState === 'playing'` and check for strictly playing by checking `playState === 'playing' && !isPending`. I've thought this many times but yesterday's experience really confirmed it for me.

The trouble, of course, is compatibility, since we've already shipped this API. On the other hand, I wonder how much code actually depends on this. For example, the code in the use case above would keep working if we dropped the `"pending"` value from `playbackState` and I suspect that >99.9% of uses of Web Animations never even look at the `playState` member.

First I'd like to know if anyone else agrees this is worth pursuing. If it is, perhaps we can add a use counter for this and then do some analysis of content.

**Comment by notoriousb1t** [comment]
I would love to see this flag implemented.  Having successfully written a timeline that wraps around individual animations, I can say that is impossible to know when inspecting the playState if it is paused or playing at any given time.  I had a real issue dealing with Chrome because they would flip to pending for a moment in certain conditions even though the animation was actually playing.  Ultimately, I had to rely on my own timeline and inspecting the playback rate to figure this out.  With an isPending flag, this would have been less error prone: https://github.com/just-animate/just-animate/blob/master/src/web/animate.ts

So, I am in favor of this proposal as it makes the API clearer and I don't think it to make a huge wave.

**Comment by birtles** [comment]
@alancutter what do you think?
CC: @dstockwell @shans

**Comment by shans** [comment]
This seems reasonable, though I do share your concern about making changes to a shipped API. I'm also not sure about how we'd detect usage meaninfully.

**Comment by birtles** [comment]
I tried to search HTTPArchive with the following query:

```sql
SELECT page, url FROM (
  SELECT 
    page, 
    url,
    JSON_EXTRACT(payload, '$._body') AS hasBody,
    JSON_EXTRACT(payload, '$._contentType') AS contentType,
    JSON_EXTRACT(payload, '$.response.content.text') AS content
  FROM [httparchive:har.2017_08_15_chrome_requests]
)
WHERE hasBody = 'true'
AND (contentType CONTAINS 'html' OR contentType CONTAINS 'javascript')
AND content CONTAINS 'anim.playbackRate'
```

but it turned up nothing. I tried again with `animation.playbackRate` and just `.playbackRate` and they turned up nothing so I'm guessing I did something wrong (although I've used a similar query before successfully).

I tried a simpler query:

```sql
SELECT 
  page, 
  url,
  body
FROM [httparchive:har.2017_08_15_chrome_requests_bodies]
WHERE body CONTAINS 'animation.playbackRate'
```

But I hit my quota before it finished. Perhaps you can run it for me?

I'll see what I can find on GitHub.

**Comment by birtles** [comment]
And now I realize I had the `playbackRate` and `playState` issues muddled up. I should have been searching for `animation.playState`.

**Comment by birtles** [comment]
Searching for ["animation playState pending"](https://github.com/search?utf8=%E2%9C%93&q=animation+playState+pending&type=Code), GitHub only shows me the first 100 pages but all I see is:

* Millions of copies of `file_animation-playstate.html`, `file_animation-finish.html`, ` file_animation-ready.html` etc.
  * These are test files (that we'll update) so they're inconsequential
* Millions of copies of `effect-callback.js` from `web-animations-js`
  * The reference here is:
     ```js
      if (playState != 'running' && playState != 'pending')
        callback._registered = false;
     ```
     Which should continue to work with the changes suggested here.

Searching for ["playState pending"](https://github.com/search?l=JavaScript&q=playState+pending&type=Code&utf8=%E2%9C%93)

* There are references in [sprite-animator](https://github.com/spritejs/sprite-animator) that seemed concerning at first (especially because there is a copy of web-animations in the `example` folder), but they all turn out to be referring to the library's own `Animator.playState` method that isn't based on Web Animations.
* `flip.js` in [vue-practice](https://github.com/aimergenge/vue-practice) likewise seemed concerning, but it also turns out to be a completely independent implementation of a property called `playState`.
* There are references in `web-animations-js`'s `player.js` test file which is copied everywhere. These shouldn't be a problem, though, I expect.
* In fact, pretty much all the hits are `player.js` or the equivalent `animation.js` from some other version of the library.
* `angular-animate.js` has references to `PlayState` but they appear to be unrelated.
* Other than that everything I could see in the first 100 pages (of which I just sampled at regular intervals) is either a test file from some version of the web-animations polyfill, or, very occasionally, a test file from the chromium repo.

**Comment by dstockwell** [comment]
I think this is worthwhile to pursue. I'm wondering about a different API, which might also sidestep the compatibility issue -- how about adding a secondary flag for the `pendingPlayState` to indicate what `playState` will become after any pending change is complete. Unless you define a new enum, that wouldn't let you know when the pending operation is a playbackrate-change, but I'm not sure when that would be necessary anyway.

**Comment by birtles** [comment]
Yeah, I wondered about that too. Obviously it wouldn't automatically fix the code in throbber use case (unlike dropping the "pending" state would). You'd need to change it so that it checks `playState === 'running' || pendingPlayState === 'running'`.

We could make `pendingPlayState === playState` when not pending so you'd only have to check `pendingPlayState === 'pending'` but it's a bit semantically awkward to have a `pendingPlayState` when you're not pending.

To a casual reader of the API `isPending` (or something of that sort) seems a little more self-explanatory to me at least.

Strictly speaking, the spec doesn't require that you go through the "pending" state at all when playing/pausing, so if there exists any code that is depending on seeing the "pending" state from `playState`, then I'd suggest it's already broken and it would be better to find that out now and make the API resilient to that, rather than, say, wait until Edge brings out an implementation that skips the "pending" state and have the content break then.

**Comment by birtles** [comment]
Discussed with @shans and @dstockwell at BlinkOn on Sep 20 who agreed with making this change.

**Comment by birtles** [comment]
I've started working on this [in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1412765) and will make a spec patch in the next few days. I'm thinking of calling the member just `pending` instead of `isPending`.

**Comment by birtles** [comment]
I haven't received any feedback on 9e2053f5534d69cebeb73359f08a172f2290272f so I'll just go ahead and merge it later today.

**Comment by birtles** [comment]
Looks like I got this wrong. The play state needs to reflect whether we have a pending task or not, otherwise we'll report "paused" when we're play-pending (since we'll have a current time but no start time). So perhaps the "play state" needs to be defined as something like:

* The current time of animation is unresolved and it does not have a pending play task or a pending pause task,
  * → idle
* The start time of animation is unresolved or it has a pending pause task,
  * → paused
* For animation, animation playback rate > 0 and current time ≥ target effect end; or
animation playback rate < 0 and current time ≤ 0,
  * → finished
* Otherwise,
  * → running

That would open up the possibility of a "finished-pending" animation, i.e. an animation that reports `anim.playState === 'finished' && anim.pending` if you had a zero-duration animation and called `play()` on it, but I *think* that might be right.

**Comment by birtles** [comment]
Hopefully fixed now!
