### ISSUE TITLE
[web-animations-1] Current time calculation has odd interaction with ScrollTimeline

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/web-animations#204]
According to the spec, current time is calculated as:

`current time = (timeline time - start time) × playback rate`

This makes sense for DocumentTimeline, where we want to provide an offset from the start of the animation, but it doesn't seem to make sense for a ScrollTimeline (https://wicg.github.io/scroll-animations/#scrolltimeline-interface). Consider the following case:

```
let effect = new KeyframeEffect(
    foo,
    [ { width: "0vw" }, { width: "100vw" } ],
    { duration: 1000, easing: "linear" });
let timeline = new ScrollTimeline({
    scrollSource: document.documentElement,
    orientation: "block",
    range: "auto"
});
let anim1 = new Animation(effect, timeline);
anim1.play();

document.documentElement.scrollTop = "50vh";
let anim2 = new Animation(effect, timeline);
anim2.play();

// According to the spec:
anim1.currentTime == 500
anim2.currentTime == 0
```

The start time is set from the timeline time. This means that if the user manages to scroll the `scrollSource` before the animation setup script runs (e.g. perhaps because the script has not yet loaded over the network), the animation will be offset by whatever value the user has already scrolled - which I don't think is what the developer would want.

A first thought (courtesy of majidvp@) is to differentiate between montonic (use start offset) and non-monotonic (don't use start offset) timelines. DocumentTimeline is obviously monotonic, whereas ScrollTimeline isn't.

**Comment by birtles** [comment]
#174 is possibly related.

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2075
