### ISSUE TITLE
Is the ready promise replaced when we go from Idle to Pending?

### ISSUE THREAD

**Issue by dstockwell** [w3c/web-animations#43]
Current spec text:

> The object is replaced with a new Promise object every time the player enters the pending play state as well as when the player is cancelled

But this means the Promise object that exists when the Player is in the idle play state will never be resolved or rejected.

I'm currently implementing the ready promise as:

> The object is replaced with a new Promise when player enters the pending play state provided it was not previously in the idle play state, as well as every time the the player is cancelled.

**Comment by birtles** [comment]
Did you see the paragraph above that?
> The current ready promise is initially a resolved Promise created using the procedure to create a new resolved Promise.
> http://w3c.github.io/web-animations/#current-ready-promise

**Comment by birtles** [comment]
For other transitions to the idle state such as cancelling a player, we initialize the ready promise to a new resolved Promise object: http://w3c.github.io/web-animations/#reset-a-players-pending-tasks

**Comment by dstockwell** [comment]
> Did you see the paragraph above that?

Oops, I did miss that.

**Comment by dstockwell** [comment]
Seems reasonable.
