### ISSUE TITLE
Make the spec work over HTTPS and update links elsewhere to use that

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#52]

**Comment by birtles** [comment]
Problem appears to be the reference to http://dev.w3.org/fxtf/default.css
I can't find an HTTPS mirror of that content though

**Comment by dstockwell** [comment]
This might work: https://hg.fxtf.org/drafts/raw-file/16b017bf3971/default.css

**Comment by birtles** [comment]
Sweet, yeah, or even https://hg.fxtf.org/drafts/raw-file/default/default.css

**Comment by birtles** [comment]
Better still, https://drafts.fxtf.org/default.css

**Comment by birtles** [comment]
I updated areweanimated yet but couldn't fix the redirects in the mercurial repository since my authorization doesn't seem to work anymore.
