### ISSUE TITLE
Convert <div class="figure"> to <figure> (and <figcaption> too)

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#59]
I think we didn't do this initially because respec didn't because some versions of IE don't allow restyling unrecognized elements. Need to check if this still matters.

**Comment by birtles** [comment]
Fixed in changeset 4f46b181a0f776644ed9ac9550722e670173437c

**Comment by tabatkins** [comment]
Those were very old IE versions (I think IE7), and the actual effect is that unrecognized elements were parsed as void (and the end tags were thrown out), unless you'd called createElement() for them earlier in the page.  Thus the common shim from back then of doing a document.createElement() for all the new HTML elements in a blocking script in your head.

It's def not relevant any longer.
