### ISSUE TITLE
[web-animations-2] Groups / AnimationNodeList should be iterable

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#67]
Need guidance on how this should best be represented. Do we still event want AnimationNodeList?

**Comment by majido** [comment]
FWIW, we were looking at using GroupEffects for Animation Worklet (incoming proposal soon) and the use of AnimationNodeList seemed unnecessary and not very ergonomic. So +1 to just make it a sequence.

@bfgeek @flackr

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2044
