### ISSUE TITLE
Check semantics for getAnimationPlayers()

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#68]
See thread starting:
https://lists.w3.org/Archives/Public/public-fx/2014AprJun/0089.html

We need to be sure getAnimationPlayers() has the right semantics we want before we ship it.  Currently it returns a new Array object every time. Some alternatives include:
* Returning the same object every time until something changes
* Returning some live list object

I'm not sure how much a live object would give you. For example, suppose you want to wait until all animations have finished on an element before triggering some UI step.  You would currently do something like this:

```js
Promise.all(elem.getAnimationPlayers().map(player => player.finished)).then(...);
```

The trouble is, if new animations happen in the meantime they won't get incorporated in the result. However, if it getAnimationPlayers() returned a live object, you'd have the same problem. So I don't know that having a live object really gets you much, at least not for this case. (For this particular case, if it's common enough, adding an "animationsFinished" promise to the Animatable interface might be useful.)

Probably need @heycam's input on this.
Also, some people find the naming Java-ish and have suggested this should be an attribute. Need to check the state of the art here (e.g. can sequences be attributes now, should they be, etc.)

**Comment by birtles** [comment]
It turns out FrozenArrays are coming and that's probably what we should use here. Need to check on their timeframe, though.

**Comment by birtles** [comment]
The "spec" is here: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23682#c25
Following up with @heycam re the expected timeframe for landing this

**Comment by heycam** [comment]
I am going to schedule the array work for April.

**Comment by birtles** [comment]
Thanks!

**Comment by birtles** [comment]
Deferred until the WebIDL work is done (and tracked in issue #76).
