### ISSUE TITLE
Tween SVG path description attribute (d)

### ISSUE THREAD

**Issue by peteschaffner** [w3c/web-animations#69]
Not sure if this is on the road map, but it would be extremely powerful, and would move us that much closer to SMIL feature parity.

**Comment by birtles** [comment]
Web Animations provides the hooks for this, but a future version of SVG simply needs to specify which attributes are animatable in terms of those hooks.

Specifically, this section:
"For DOM attributes, the animation behavior is defined alongside the attribute definition. Unlike CSS properties, if such a definition is not provided the default animation behavior is “not animatable”."
(http://w3c.github.io/web-animations/#specific-animation-behaviors)

I think this isn't an issue with the Web Animations spec so I'm closing this for now. Let me know if you disagree.

**Comment by stuartpb** [comment]
The quoted text doesn't seem to be present in the current version of the specification.

**Comment by birtles** [comment]
DOM attributes are no longer animatable from Web Animations. Instead, attributes that need to be animated should be promoted to properties. The the 'd' attribute, SVG 2 promotes it to a property: https://svgwg.org/svg2-draft/paths.html#TheDProperty
