### ISSUE TITLE
animation end time calculation seems incorrect

### ISSUE THREAD

**Issue by dstockwell** [w3c/web-animations#86]
The end time of an animation can be before its start time,

*The end time of an animation effect is simply the sum of its start time, start delay, active duration, and end delay*

But consider negative startDelay/endDelay larger than active duration.

**Comment by dstockwell** [comment]
For now, implementing end time as the max of start time and the above calculation, but it's easy to change this.

**Comment by birtles** [comment]
Yep, the change you suggest sounds right to me.

**Comment by birtles** [comment]
Now, having made this change, I wonder if it's right. @dstockwell, what's wrong with having the end time before the start time?

**Comment by dstockwell** [comment]
Hmm, I was mostly worried about the animation reaching the finished state. I think, without this or some other changes, there are still some weird cases where the animation can get into the finished state with a currentTime < 0.

**Comment by birtles** [comment]
Yeah, I'm trying to work out what those weird cases are. I think it would be fine for an animation to get into the finished state with a currentTime < 0. In fact, you can already do that just by setting playbackRate to something negative.

There doesn't seem to be anything in CSS animations preventing animations from having a large negative delay to make them begin in the finished state.

I think it's useful to be able to use the start delay to move the animation anywhere on the timeline.

But I'm probably overlooking something. So if you can find some of those weird cases, that would be really helpful.

**Comment by birtles** [comment]
@dstockwell I'm thinking of reverting this change. Did you find any cases that are fixed by this?

**Comment by birtles** [comment]
Discussed this change. There don't appear to be any cases that are fixed by this so we can revert this change.

**Comment by birtles** [comment]
I'm currently implementing this change in Gecko and if there's no problem I'll update the spec:
https://bugzilla.mozilla.org/show_bug.cgi?id=1249212

Of course, we don't implement endDelay yet so we might have bigger problems once we do that.
