### ISSUE TITLE
The id for the AnimationEffectReadonly interface is #the-animationnode-interface

### ISSUE THREAD

**Issue by foolip** [w3c/web-animations#88]
This is strange, should be #the-animationeffectreadonly-interface

**Comment by foolip** [comment]
It seems like this is not the only one. http://w3c.github.io/web-animations/#the-animationtimingreadonly-interface is for the AnimationEffectTimingReadonly interface.

If the old ids are kept to not break existing links, having those as hidden anchors that aren't linked from anywhere in the spec might achieve the same goal.

**Comment by foolip** [comment]
Another: https://w3c.github.io/web-animations/#the-computedanimationtiming-interface should be #the-computedanimationtiming-dictionary

**Comment by birtles** [comment]
Thanks for reporting this!

**Comment by foolip** [comment]
Thanks for the quick fixes! I found a few more but will open a separate issue as I don't seem to have the power to reopen this one.
