### ISSUE TITLE
Animating non-DOMs

### ISSUE THREAD

**Issue by tobireif** [w3c/web-animations#94]
Dear Web Animations Team

Web Animations are intended to be used with HTML and eg SVG (please correct me if I'm wrong).

Can they also be used to animate non-DOMs? It would be great if the spec would support animating any type of value, of any property, of any JS object.

For example: If I use eg Pixi JS, can I use Web Animations directly to animate sprite.alpha ?

If that currently is not the case, please consider broadening the scope of the spec to accommodate this versatility.

Tobi

**Comment by tobireif** [comment]
This this acceptable as a place for such questions/suggestions?

**Comment by birtles** [comment]
Sorry, the public-fx mailing list is probably better for this.
Arbitrary properties can be animated using custom effects. This has been deferred until level 2 of the specification.

**Comment by tobireif** [comment]
Hi Brian

(Since this issue will be resolved in a future version of the spec I won't re-post it on the mailing list.)

Great to hear that W3C Web Animations will support animating any property of any JS object.

But because it won't happen until level 2, I will (at least until then) continue to use my own tiny JS ani lib  (especially for non DOM targets such as Pixi JS sprites).
(... and perhaps one of the existing tween libs [1].)

Looking forward to a more universally applicable Web Animations spec,

Tobi

[1] Some of the existing tween/ani libs:
https://github.com/CreateJS/TweenJS
https://github.com/tweenjs/tween.js
http://greensock.com/tweenmax
https://github.com/julianshapiro/velocity
